[cockpit.geqip.dem]
editable = false

[[cockpit.geqip.dem.layout]]
x = 0
y = 0
w = 16
h = 2
i = 0
show_title = true
title = ""
w_class = "simple_text"

[cockpit.geqip.dem.layout.w_params]
text = "GEQIP cockpit"
text_color = "#000000"
font_size = 48
background_color = "#ddd"

[[cockpit.geqip.dem.layout]]
x = 0
y = 2
w = 4
h = 7
i = 1
title = "Plan biomédical (nb)"
w_class = "nb_previsionnel_par_expert"
w_params = "{\"discipline\":\"BM\"}"

[[cockpit.geqip.dem.layout]]
x = 4
y = 2
w = 4
h = 7
i = 2
title = "Plan biomédical (€)"
w_class = "montant_previsionnel_par_expert"
w_params = "{\"discipline\":\"BM\"}"

[[cockpit.geqip.dem.layout]]
x = 8
y = 2
w = 4
h = 7
i = 3
title = "Plan équipements (nb)"
w_class = "nb_previsionnel_par_expert"
w_params = "{\"discipline\":\"EQ\"}"

[[cockpit.geqip.dem.layout]]
x = 12
y = 2
w = 4
h = 7
i = 4
title = "Plan équipements (€)"
w_class = "montant_previsionnel_par_expert"
w_params = "{\"discipline\":\"EQ\"}"
