[options]
magh2_orders = true

[[extable.tables]]
name = 'Fournisseur'
engine = 'csv'
path = 'magh2'
filename = 'last:chuap_magh2_fournisseurs.csv'

# Guessed columns types from extable_guess command
column.no_fournisseur_fr = { type = "integer", src_column = "No Fournisseur (fr)" }
column.intitule_fournisseur_fr = { type = "string", src_column = "Intitulé Fournisseur (fr)" }
column.raison_sociale_fournisseur_fr = { type = "string", src_column = "Raison sociale Fournisseur (fr)" }

key = ['no_fournisseur_fr']

[[extable.tables]]
name = 'Commande'
engine = 'csv'
path = 'magh2'
filename = 'all:commandes/chuap_*.csv'

# Guessed columns types from extable_guess command
column.gest_ec = { type = "string", src_column = "Gest. (ec)" }
column.no_cde_ec = { type = "integer", src_column = "No Cde (ec)" }
column.exercice_ec = { type = "integer", src_column = "Exercice (ec)" }
column.no_marche_ma = { 'optional' = true, type = "integer", src_column = "No Marché (ma)" }
column.nomenclature_lc = { 'optional' = true, type = "float", src_column = "Nomenclature (lc)" }
# column.no_fournisseur_fr = {type = "integer", src_column = "No Fournisseur (fr)"}
column.fournisseur = { 'optional' = true, type = "foreign_key", src_column = "No Fournisseur (ma2)", foreign_table = "extable.ExtFournisseur", foreign_column = "no_fournisseur_fr" }
# column.intitule_fournisseur_fr = {type = "string", src_column = "Intitulé Fournisseur (fr)"}
column.date_passation_ec = { 'optional' = true, type = "datetime", src_column = "Date Passation (ec)" }
column.objet_depense_ec = { 'optional' = true, type = "string", src_column = "Objet Dépense (ec)" }
column.no_ligne_lc = { type = "integer", src_column = "No Ligne (lc)" }
column.no_uf_uf = { 'optional' = true, type = "integer", src_column = "No UF (uf)" }
column.libelle_uf_uf = { 'optional' = true, type = "string", src_column = "Libellé UF (uf)" }
column.compte_ordonnateur_cp = { 'optional' = true, type = "string", src_column = "No Compte (cp)" }
column.no_compte_cp = { 'optional' = true, type = "string", src_column = "No Compte (cp)" }
column.libelle_l1_lc = { 'optional' = true, type = "string", src_column = "Libellé L1 (lc)" }
column.libelle_l2_lc = { 'optional' = true, type = "string", src_column = "Libellé L2 (lc)" }
column.libelle_l3_lc = { 'optional' = true, type = "string", src_column = "Libellé L3 (lc)" }
column.libelle_l4_lc = { 'optional' = true, type = "string", src_column = "Libellé L4 (lc)" }
column.bloc_note_1_ec = { 'optional' = true, type = "string", src_column = "Bloc Note 1 (ec)" }
column.bloc_note_2_ec = { 'optional' = true, type = "string", src_column = "Bloc Note 2 (ec)" }
column.no_operation_op = { 'optional' = true, type = "string", src_column = "No Opération (op)" }
column.lib_operation_op = { 'optional' = true, type = "string", src_column = "Lib. Opération (op)" }
column.qte_cdee_lc = { 'optional' = true, type = "integer", src_column = "Qté Cdée (lc)" }
column.qte_recue_lc = { 'optional' = true, type = "integer", src_column = "Qté Reçue (lc)" }
column.mt_engage_lc = { 'optional' = true, type = "float", src_column = "Mt Engagé (lc)" }
column.mt_liquide_lc = { 'optional' = true, type = "float", src_column = "Mt liquidé (lc)" }
column.lg_soldee_lc = { 'optional' = true, type = "string", src_column = "Lg Soldée (lc)" }
column.code_famille_lc = { 'optional' = true, type = "string", src_column = "Code Famille (lc)" }

# Add a (computed) column
column.commande = { 'type' = 'string', 'data' = 'concat(gest_ec, format("{:06d}", no_cde_ec))' }
column.libelle = { 'optional' = true, 'type' = 'string', 'data' = 'concat(libelle_l1_lc, concat("\n", concat(libelle_l2_lc, concat("\n", concat(libelle_l3_lc, concat("\n", libelle_l4_lc))))))' }
column.bloc_note = { 'optional' = true, 'type' = 'string', 'data' = 'concat(bloc_note_1_ec, concat("\n", bloc_note_2_ec))' }
# Analyse de la commande, stockée dans la première ligne de la commande
column.analyse_cmd = { 'type' = 'json', 'data' = '{}', 'format' = 'analysis' }
# Analyse de la ligne de commande
column.analyse = { 'type' = 'json', 'data' = '{}', 'format' = 'analysis' }

key = ['commande', 'no_ligne_lc']

[[extable.tables]]
name = 'Immobilisation'
path = 'magh2'
filename = "immobilisations.csv"
engine = 'csv'

# Guessed columns types from extable_guess command
column.exercice_d_acquisition_fi = { type = "integer", src_column = "Exercice d'acquisition (fi)" }
column.no_fiche_fi = { type = "integer", src_column = "No Fiche (fi)" }
column.no_uf_df = { type = "integer", src_column = "No UF (df)" }
column.libelle_uf_df = { type = "string", src_column = "Libellé UF (df)" }
column.compte_ordonnateur_cp = { type = "string", src_column = "Compte Ordonnateur (cp)" }
column.libelle_compte_cp = { type = "string", src_column = "Libellé Compte (cp)" }
column.ligne_commande_df = { type = "integer", src_column = "Ligne Commande (df)" }
column.no_interne_fi = { type = "string", src_column = "No Interne (fi)" }
column.gest_cde_df = { type = "string", src_column = "Gest Cde (df)" }
column.no_cde_df = { type = "integer", src_column = "No Cde (df)" }
column.libelle_du_bien_fi = { type = "string", src_column = "Libellé du bien (fi)" }
column.date_de_mise_en_service_fi = { type = "datetime", src_column = "Date de mise en service (fi)" }
column.mode_gest_fi1 = { type = "string", src_column = "Mode Gest (fi1)" }
column.duree_fi2 = { type = "integer", src_column = "Durée (fi2)" }
column.df_amort_fi2 = { type = "datetime", src_column = "DF Amort (fi2)" }
column.code_famille_fe = { type = "integer", src_column = "Code Famille (fe)" }
column.libelle_famille_fe = { type = "string", src_column = "Libellé Famille (fe)" }
column.repartition_fi1 = { type = "money", src_column = "Répartition (fi1)" }
column.qte_uf_df1 = { type = "integer", src_column = "Qté UF (df1)" }
column.repart_uf_df1 = { type = "integer", src_column = "Répart. UF (df1)" }
column.actif_uf_df2 = { type = "money", src_column = "Actif UF (df2)" }

column.fiche = { 'type' = 'string', 'data' = 'concat(exercice_d_acquisition_fi, concat("-", format("{:05d}", no_fiche_fi)))' }
column.code = { 'type' = 'string', 'data' = 'concat(concat(concat(exercice_d_acquisition_fi, concat("-", format("{:05d}", no_fiche_fi))), "-"), format("{:04d}", no_uf_df))' }
column.commande = { 'type' = 'string', 'data' = "concat(gest_cde_df, format('{:06d}', no_cde_df))" }
column.analyse = { 'type' = 'json', 'data' = '"{}"', 'format' = 'analysis' }
column.residuel = { 'type' = 'money', 'data' = 'residuel(actif_uf_df2,duree_fi2,date_de_mise_en_service_fi)' }

key = ['code']

#[[extable.tables]]
#name = 'Facture'
#engine = 'csv'
#path = 'prodige'
#filename = "last:export-*.csv"
#separator = ";"
#preprocess = "fix_nb_columns"

#column.type = {type = "string", src_column = "Type"}
#column.fournisseur = {type = "string", src_column = "Fournisseur"}
#column.reference_facture = {type = "string", src_column = "Référence facture"}
#column.emission = {type = "datetime", src_column = "Emission"}
#column.reception = {type = "datetime", src_column = "Réception"}
#column.n_engagement = {type = "string", src_column = "N° engagement Chorus"}
#column.montant_ttc = {type = "string", src_column = "Montant TTC"}
#column.etat = {type = "string", src_column = "Etat"}
#column.n_de_lot = {type = "string", src_column = "N° de lot"}
#column.code_service = {type = "string", src_column = "Code service"}
#column.n_liq = {type = "integer", src_column = "N° Liq."}
#column.traite_automatiquement = {type = "string", src_column = "Traité Automatiquement"}
#column.commande_magh2 = {type = "string", src_column = "Commande Magh2"}
#column.n_mandat = {type = "integer", src_column = "N° Mandat"}
#column.dernier_commentaire = {type = "string", src_column = "Dernier commentaire"}

# Add (computed) columns
#column.commande = {'type'='string', 'data'='find_magh2_order(n_engagement)'}
#column.montant_eur_ttc = {'type'='money', 'data'='to_amount(montant_ttc)'}

# column.json_order_link = {'type'='string', 'data'={'model'='Commande','conditions'={},'foreign'={'commande'='commande'}}}

# key = ['fournisseur', 'reference_facture']

[[extable.tables]]
name = 'ProcedureAchat'
engine = 'excel'
path = 'magh2'
filename = 'PointDRB.xlsx'

header_row = 2

[[extable.tables]]
name = 'Equipement'
engine = 'database'
database = 'gmao'
model = 'assetplusconnect.BEq1996'
# key = ['code']

column.code = { type = "string", src_column = "n_imma" }
column.name = { type = "string", src_column = "nom" }
column.description = { type = "string", src_column = "nom2" }
column.uf_code = { type = "string", src_column = "n_uf" }
column.n_order = { type = "string", src_column = "n_order" }
column.price = { type = "string", src_column = "prix" }
column.commissioning_date = { type = "datetime", src_column = "mes1" }
column.reform_date = { type = "datetime", src_column = "date_refor" }
column.asset_code = { type = "string", src_column = "filler_eco_3" }
column.local_code = { type = "string", src_column = "number_in_site" }

[[extable.tables]]
name = 'Dra94Previsionnel'
engine = 'tps'
path = 'dra94'
filename = 'prevision.tps'

column.record_no = { type = "integer", src_column = "RecNo'" }
column.programme = { type = "string", src_column = "PROGRAMME" }
column.ligne = { type = "integer", src_column = "LIGNE" }
column.service = { type = "string", src_column = "SERVICE" }
column.code_famille = { type = "integer", src_column = "CODEFAMILLE" }
column.qte_demandee = { type = "float", src_column = "QUANTITEDMD" }
column.intitule = { type = "string", src_column = "INTITULE" }
column.qte_acquise = { type = "float", src_column = "QUANTITEACQ" }
# column.cout_francs = {type = "money", src_column = "COUTF"}
column.cout_euros = { type = "money", src_column = "COUTE" }
column.remarque = { type = "string", src_column = "REMARQUE" }
column.cellule = { type = "string", src_column = "CELLULE" }
column.cout_realise = { type = "money", src_column = "COUTREA" }
column.solde = { type = "integer", src_column = "SOLDE" }
column.code_uf = { type = "integer", src_column = "UF" }

key = ['record_no']

[[extable.tables]]
name = 'Dra94Dossier'
engine = 'tps'
path = 'dra94'
filename = 'DOSSIER.TPS'

column.record_no = { type = "integer", src_column = "RecNo'" }
column.numero = { type = "integer", src_column = "NUMERO" }
column.date_dossier = { type = "datetime", src_column = "DATEDOSSIER" }
column.fournisseur = { type = "string", src_column = "fourniss" }
column.code_fournisseur = { type = "float", src_column = "codefouratelier" }
column.point = { type = "float", src_column = "point" }
column.contact_fournisseur = { type = "string", src_column = "NOMSTE" }
column.numero_devis = { type = "string", src_column = "NDEVIS" }
column.date_devis = { type = "datetime", src_column = "DATEDEVIS" }
column.montant = { type = "money", src_column = "MONTANTE" }
column.code_famille = { type = "integer", src_column = "codefamille" }
column.contact = { type = "string", src_column = "contact" }
column.contact_livraison = { type = "string", src_column = "contactlivraison" }
column.numero_compte = { type = "string", src_column = "compte" }
column.ugap = { type = "string", src_column = "UGAP" }
column.programme = { type = "string", src_column = "NPROG" }
column.ligne = { type = "float", src_column = "ligne" }
column.divers = { type = "string", src_column = "DIVERS" }
column.dsio = { type = "integer", src_column = "dsio" }
column.transmis = { type = "datetime", src_column = "transmis" }
column.no_commande = { type = "string", src_column = "bon_commande" }
column.date_commande = { type = "datetime", src_column = "datecde" }
column.fin_dossier = { type = "integer", src_column = "fin_dossier" }
column.cellule = { type = "string", src_column = "cellule" }
column.no_marche = { type = "string", src_column = "n_marche" }
column.imprime = { type = "integer", src_column = "imprime" }
column.pieces_jointes = { type = "integer", src_column = "piecejointe" }

key = ['record_no']

[[extable.tables]]
name = 'Dra94Ligne'
engine = 'tps'
path = 'dra94'
filename = 'ACHAT_new.TPS'

column.record_no = { type = "integer", src_column = "RecNo'" }
column.departement = { type = "string", src_column = "DEPARTEMENT" }
column.date_dossier = { type = "datetime", src_column = "DATEDOSSIER" }
column.tri = { type = "string", src_column = "TRI" }
column.numero_dossier = { type = "integer", src_column = "NUMERO" }
column.dossier = { type = "foreign_key", src_column = "NUMERO", foreign_table = "extable.ExtDra94Dossier", foreign_column = "numero" }
column.code_uf = { type = "string", src_column = "N_UF" }
column.cadre = { type = "string", src_column = "SURVEILLANT" }
column.designation = { type = "string", src_column = "DESIGN" }
column.designation_cneh = { type = "string", src_column = "DESIGN_CNEH" }
column.code_cneh = { type = "string", src_column = "CNEH" }
column.specificite = { type = "string", src_column = "SPECIFICITE" }
column.type_modele = { type = "string", src_column = "TYPE" }
column.reference = { type = "string", src_column = "REFERENCE" }
column.quantite = { type = "float", src_column = "QTE" }
column.accessoires = { type = "string", src_column = "ACCESS" }
column.fournisseur = { type = "string", src_column = "FOURNISS" }
column.contact_fournisseur = { type = "string", src_column = "NOMSTE" }
column.equipement_a_recuperer = { type = "string", src_column = "EQUIP_RECUP" }
column.mutation_reforme = { type = "string", src_column = "MUTATION_REF" }
column.service = { type = "string", src_column = "SERVICE" }
column.formation = { type = "string", src_column = "FORMATION" }
column.visite_fin_garantie = { type = "string", src_column = "VISITE_FIN_G" }
column.pu_ttc = { type = "money", src_column = "PTTCE" }
column.code_uf_mutation = { type = "string", src_column = "NUF_MUT" }
column.service_miutation = { type = "string", src_column = "SRV_MUT" }
column.sct_mutation = { type = "string", src_column = "SCT_MUT" }
column.montant = { type = "money", src_column = "TOTALE" }
column.no_reforme = { type = "float", src_column = "REFORME" }
column.duree_garantie = { type = "float", src_column = "DUREE_GARANTIE" }
column.jours_formation = { type = "float", src_column = "JOUR_FORM" }
column.site = { type = "string", src_column = "SITE" }
column.dsio = { type = "float", src_column = "DSIO" }
column.direction = { type = "string", src_column = "DIRECTION" }
column.rubrique = { type = "string", src_column = "RUBRIQUE" }
column.annee_rubrique = { type = "float", src_column = "ANNEERUB" }
column.choix = { type = "string", src_column = "CHOIX" }
column.cout_maintenante = { type = "money", src_column = "MAINTENANCE_E" }
column.supplementaire = { type = "string", src_column = "SUPPLEMENTAIRE" }
column.marque = { type = "string", src_column = "MARQUE" }
column.remise = { type = "float", src_column = "REMISE" }
column.pu_ht = { type = "money", src_column = "PUHTE" }
column.gain_ht = { type = "money", src_column = "GAIN" }
column.date_reception = { type = "datetime", src_column = "DATE_RECEPTION" }
column.date_mise_en_service = { type = "datetime", src_column = "DATE_SERVICE" }
column.recu = { type = "string", src_column = "RECU" }
column.installe = { type = "string", src_column = "INSTALL" }
column.taux_tva = { type = "float", src_column = "TAUXTVA" }
column.contrat = { type = "string", src_column = "CONTRAT" }
column.classe = { type = "string", src_column = "CLASSE" }

key = ['record_no']
